CREATE TABLE TAB_USUARIO (
 ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 EMAIL VARCHAR(255) NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 NOME_COMPLETO VARCHAR(100) NOT NULL,
 CPF VARCHAR(14) NOT NULL
);

CREATE TABLE TAB_ENDERECO (
 ID_USUARIO INT,
 ID_ENDERECO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 RUA VARCHAR(255) NOT NULL,
 NUMERO INT NOT NULL,
 BAIRRO VARCHAR(130) NOT NULL,
 COMPLEMENTO VARCHAR(100) NOT NULL,
 CEP VARCHAR(10) NOT NULL
);

CREATE TABLE TAB_PRODUTO (
 ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 NOME VARCHAR(70),
 PRECO FLOAT NOT NULL,
 DESCRICAO VARCHAR(500),
 QUANTIDADE INT,
 IMAGEM VARCHAR(250)
);

CREATE TABLE TAB_COMPRA (
 ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
 VALOR FLOAT NOT NULL,
 FRETE FLOAT NOT NULL,
 VALOR_TOTAL FLOAT NOT NULL,
 DATA_COMPRA DATE NOT NULL,
 ID_USUARIO INT,
 ID_ENDERECO INT,
 ID_PAGAMENTO INT
);

CREATE TABLE TAB_PAGAMENTO(
 ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
 NUMERO_CARTAO VARCHAR(16) NOT NULL,
 DATA_EXPIRACAO VARCHAR(12) NOT NULL,
 CVV INT NOT NULL,
 NOME_COMPLETO VARCHAR(100) NOT NULL,
 CPF VARCHAR(14) NOT NULL
);

CREATE TABLE COMPRA_PRODUTO(
 ID_COMPRA INT,
 ID_PRODUTO INT
);

ALTER TABLE TAB_ENDERECO ADD FOREIGN KEY(ID_USUARIO) REFERENCES TAB_USUARIO(ID_USUARIO);
ALTER TABLE TAB_COMPRA ADD FOREIGN KEY(ID_USUARIO) REFERENCES TAB_USUARIO(ID_USUARIO);
ALTER TABLE TAB_COMPRA ADD FOREIGN KEY(ID_ENDERECO) REFERENCES TAB_ENDERECO(ID_ENDERECO);
ALTER TABLE TAB_COMPRA ADD FOREIGN KEY(ID_PAGAMENTO) REFERENCES TAB_PAGAMENTO(ID_PAGAMENTO);
ALTER TABLE COMPRA_PRODUTO ADD FOREIGN KEY(ID_COMPRA) REFERENCES TAB_COMPRA(ID_COMPRA);
ALTER TABLE COMPRA_PRODUTO ADD FOREIGN KEY(ID_PRODUTO) REFERENCES TAB_PRODUTO(ID_PRODUTO);