CREATE TABLE TAB_USUARIO
(
 ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 EMAIL VARCHAR(255) NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 NOME_COMPLETO VARCHAR(100) NOT NULL,
 CPF VARCHAR(14) NOT NULL,
 UNIQUE (email)
);

CREATE TABLE TAB_ENDERECO
(
 ID_USUARIO INT,
 ID_ENDERECO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 RUA VARCHAR(255) NOT NULL,
 NUMERO INT NOT NULL,
 BAIRRO VARCHAR(130) NOT NULL,
 COMPLEMENTO VARCHAR(100) NOT NULL,
 CEP VARCHAR(10) NOT NULL
);

--CREATE TABLE Compra
--(
-- idUsuario INT,
-- idEndereco INT,
-- idPagamento INT,
-- idProduto INT,
-- idCompra INT PRIMARY KEY AUTO_INCREMENT,
--);

--CREATE TABLE Produto
--(
-- idProduto INT PRIMARY KEY AUTO_INCREMENT,
--);
--
--CREATE TABLE Pagamento
--(
-- idPagamento INT PRIMARY KEY AUTO_INCREMENT,
--);

ALTER TABLE TAB_ENDERECO ADD FOREIGN KEY(ID_USUARIO) REFERENCES TAB_USUARIO (ID_USUARIO)
--ALTER TABLE Compra ADD FOREIGN KEY(idUsuario) REFERENCES Usuario (idUsuario)
--ALTER TABLE Compra ADD FOREIGN KEY(idEndereco) REFERENCES Endereco (idEndereco)
--ALTER TABLE Compra ADD FOREIGN KEY(idPagamento) REFERENCES Pagamento (idPagamento)
--ALTER TABLE Compra ADD FOREIGN KEY(idProduto) REFERENCES Produto (idProduto)
